package org.red5.server.api;

/**
 * The client object represents a single client.
 * One client may have mutiple connections to different scopes on the same host.
 * In some ways the client object is like a http session. 
 * 
 * NOTE: I removed session, since client serves the same purpose as a client with attributes
 * 
 * @author The Red5 Project (red5@osflash.org)
 * @author Luke Hubbard (luke@codegent.com)
 */
public interface Client extends AttributeStore {

	/**
	 * The key used to store the client object in a http session
	 */
	public static final String HTTP_SESSION_KEY = "red5.client";
	
	/**
	 * Get the unique ID for this client, this will be generated by the server if not passed with connect
	 * 
	 *  @return String containing the id
	 */
	public String getId();
	
	/**
	 * Get the hostname that the client connected to.
	 * If they connected to an IP, the IP address will be returned as a String.
	 * 
	 * @return String containing the hostname
	 */
	public String getHost();
	
	/**
	 * Get the creation time for this client object
	 * 
	 * @return long represnting the time in milliseconds when this object was created
	 */
	public long getCreationTime();

	/**
	 * Lookup a connection associated with a given scope
	 * 
	 * @param scope	the current scope object
	 * @return	connection	the associated connection object
	 */
	public Connection lookupConnection(Scope scope);
	
}